// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MvvmHelper
{
    internal sealed partial class Vsix
    {
        public const string Id = "MvvmHelper.c868b469-87ba-4c22-817b-aa011e5019d7";
        public const string Name = "MvvmHelper";
        public const string Description = @"Generate ViewModels";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lijianing";
        public const string Tags = "";
    }
}
