// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MvvmHelper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string uiContextSupportedFilesString = "660bc25f-3a95-48e6-ac0d-a8b8eda0fbce";
        public static Guid uiContextSupportedFiles = new Guid(uiContextSupportedFilesString);

        public const string MvvmHelperString = "748cdac9-0003-441c-9e0e-402953e3526e";
        public static Guid MvvmHelper = new Guid(MvvmHelperString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int GenerateViewModelCommand = 0x0100;
    }
}